/**
 * Failed-transactions CSV export (spec §6.4, TRK-004/005/006, AC-18).
 *
 * Three properties this module exists to guarantee:
 *
 *  1. **Authoritative source.** The builder accepts ledger rows only. There is no code
 *     path that serialises client-supplied state — NFR-DATA-002.
 *  2. **Traceable identifiers preserved.** Receipt, ConversationID and
 *     OriginatorConversationID are always columns, so a row in this file can be taken to
 *     Safaricom support and matched exactly.
 *  3. **Formula-injection safe.** A recipient named `=cmd|'/c calc'!A1` must not execute
 *     when finance opens the export in Excel. Every field that begins with a formula
 *     trigger is prefixed with a single quote and the value is quoted.
 */

import type { TxnState } from './txn-state.js';
import { formatCents } from './money.js';

/** One authoritative ledger row, as selected by the export query. */
export interface TransactionExportRow {
  batchReference: string;
  batchId: string;
  instructionId: string;
  recipientName: string;
  msisdn: string;
  departmentName: string | null;
  amountCents: number;
  status: TxnState;
  failureCode: string | null;
  failureReason: string | null;
  providerResultDescription: string | null;
  mpesaReceiptNumber: string | null;
  conversationId: string | null;
  originatorConversationId: string | null;
  submittedAt: string | null;
  lastUpdatedAt: string;
  lastStatusCheckAt: string | null;
  statusSource: string | null;
}

/** Column order is part of the contract: downstream finance macros depend on it. */
export const FAILED_EXPORT_HEADERS = [
  'BatchReference',
  'BatchID',
  'InstructionID',
  'RecipientName',
  'MSISDN',
  'Department',
  'AmountKES',
  'Status',
  'FailureCode',
  'FailureReason',
  'ProviderResultDescription',
  'MPESAReceiptNo',
  'ConversationID',
  'OriginatorConversationID',
  'SubmittedAt',
  'LastUpdatedAt',
  'LastStatusCheckAt',
  'StatusSource',
] as const;

const FORMULA_TRIGGER = /^[=+\-@\t\r]/;

/**
 * Escape one CSV field.
 *
 * The leading apostrophe on formula-triggering values is the documented Excel/LibreOffice
 * mitigation for CSV injection (OWASP). It is applied to *all* text fields, not only names,
 * because provider descriptions are attacker-influenced too.
 */
export function escapeCsvField(value: string | number | null | undefined): string {
  if (value === null || value === undefined) return '';
  let text = String(value);
  if (text === '') return '';
  if (FORMULA_TRIGGER.test(text)) text = `'${text}`;
  if (/[",\n\r]/.test(text)) {
    return `"${text.replace(/"/g, '""')}"`;
  }
  return text;
}

export function buildCsvLine(fields: readonly (string | number | null | undefined)[]): string {
  return fields.map(escapeCsvField).join(',');
}

export interface ExportMetadata {
  exportId: string;
  organizationId: string;
  generatedAt: string;
  generatedByUserId: string;
  generatedByLevel: string;
  /** The explorer filter that produced this set — recorded in the audit event. */
  filterDescription: string;
  rowCount: number;
}

/**
 * Render the export.
 *
 * A short provenance header precedes the data. It is commented with `#` so spreadsheet
 * imports can skip it, and it exists because a CSV emailed around a finance team with no
 * indication of who produced it, when, or under what filter is an audit problem waiting to
 * happen.
 */
export function renderFailedTransactionsCsv(
  rows: readonly TransactionExportRow[],
  metadata: ExportMetadata,
  options: { includeProvenanceHeader?: boolean } = {},
): string {
  const includeHeader = options.includeProvenanceHeader ?? true;
  const lines: string[] = [];

  if (includeHeader) {
    lines.push(`# SOLVAREN Payment Solutions — failed transactions export`);
    lines.push(`# Export ID: ${metadata.exportId}`);
    lines.push(`# Generated at: ${metadata.generatedAt}`);
    lines.push(`# Generated by: ${metadata.generatedByUserId} (${metadata.generatedByLevel})`);
    lines.push(`# Filter: ${metadata.filterDescription.replace(/[\r\n]+/g, ' ')}`);
    lines.push(`# Rows: ${metadata.rowCount}`);
    lines.push(`# Source: authoritative payment ledger. Amounts in KES.`);
  }

  lines.push(FAILED_EXPORT_HEADERS.join(','));

  for (const r of rows) {
    lines.push(
      buildCsvLine([
        r.batchReference,
        r.batchId,
        r.instructionId,
        r.recipientName,
        r.msisdn,
        r.departmentName,
        formatCents(r.amountCents),
        r.status,
        r.failureCode,
        r.failureReason,
        r.providerResultDescription,
        r.mpesaReceiptNumber,
        r.conversationId,
        r.originatorConversationId,
        r.submittedAt,
        r.lastUpdatedAt,
        r.lastStatusCheckAt,
        r.statusSource,
      ]),
    );
  }

  // Trailing newline: POSIX tools and some spreadsheet importers drop the final row without it.
  return lines.join('\r\n') + '\r\n';
}

/** Content-Disposition filename. Deterministic and safe for every filesystem. */
export function exportFilename(prefix: string, organizationSlug: string, generatedAt: string): string {
  const stamp = generatedAt.replace(/[:.]/g, '-').replace('T', '_').replace('Z', '');
  const slug = organizationSlug.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 40);
  return `${prefix}_${slug || 'organization'}_${stamp}.csv`;
}
