import { describe, it, expect } from 'vitest';
import {
  renderFailedTransactionsCsv,
  escapeCsvField,
  exportFilename,
  FAILED_EXPORT_HEADERS,
  renderReportCsv,
  formatReportCell,
  type TransactionExportRow,
  type ExportMetadata,
  type ReportDocument,
} from './export-csv.js';
import { instructionFingerprint } from './idempotency.js';
import {
  explorerQuerySchema,
  buildOrderBy,
  describeFilter,
  assertCoherentRange,
  pageInfo,
  offsetFor,
  SORT_COLUMNS,
  MAX_PAGE_SIZE,
} from './explorer.js';
import {
  assessBatchRisk,
  DEFAULT_RISK_POLICY,
  type RecipientHistory,
  type InstructionForRisk,
} from './risk.js';

const row = (o: Partial<TransactionExportRow> = {}): TransactionExportRow => ({
  batchReference: 'SLV-2026-00981',
  batchId: '8f2a-batch',
  instructionId: 'ins-001',
  recipientName: 'Jane Doe',
  msisdn: '254712345678',
  departmentName: 'Engineering',
  amountCents: 45_000_00,
  status: 'FAILED',
  failureCode: '1',
  failureReason: "Insufficient balance in the organization's Utility account",
  providerResultDescription: 'The balance is insufficient for the transaction',
  mpesaReceiptNumber: null,
  conversationId: 'AG_20260913_20106e9209f64bebd05b',
  originatorConversationId: '600997-INS001-9F3KQ9ZB',
  submittedAt: '2026-09-13T08:30:00.000Z',
  lastUpdatedAt: '2026-09-13T08:31:12.000Z',
  lastStatusCheckAt: '2026-09-13T09:00:00.000Z',
  statusSource: 'CALLBACK',
  ...o,
});

const metadata: ExportMetadata = {
  exportId: 'EXP-2026-7F3KQ9ZB',
  organizationId: 'org-1',
  generatedAt: '2026-09-13T09:15:00.000Z',
  generatedByUserId: 'user-l2',
  generatedByLevel: 'L2',
  filterDescription: 'status in [FAILED]; batch SLV-2026-00981',
  rowCount: 1,
};

describe('failed-transactions CSV export (§6.4, AC-18)', () => {
  it('emits every required column in the documented order', () => {
    const csv = renderFailedTransactionsCsv([row()], metadata);
    const headerLine = csv.split('\r\n').find((l) => l.startsWith('BatchReference'));
    expect(headerLine).toBe(FAILED_EXPORT_HEADERS.join(','));
    for (const required of [
      'FailureCode',
      'FailureReason',
      'MPESAReceiptNo',
      'ConversationID',
      'OriginatorConversationID',
    ]) {
      expect(headerLine).toContain(required);
    }
  });

  it('TRK-005: preserves provider reference identifiers verbatim', () => {
    const csv = renderFailedTransactionsCsv([row()], metadata);
    expect(csv).toContain('AG_20260913_20106e9209f64bebd05b');
    expect(csv).toContain('600997-INS001-9F3KQ9ZB');
  });

  it('includes the failure code and the human-readable reason on the data row', () => {
    const csv = renderFailedTransactionsCsv([row()], metadata);
    const dataLine = csv.split('\r\n').find((l) => l.startsWith('SLV-2026-00981'))!;
    expect(dataLine).toContain('FAILED');
    expect(dataLine).toContain('Utility account');
  });

  it('records provenance so a circulated file is traceable (TRK-006)', () => {
    const csv = renderFailedTransactionsCsv([row()], metadata);
    expect(csv).toContain('# Export ID: EXP-2026-7F3KQ9ZB');
    expect(csv).toContain('# Generated by: user-l2 (L2)');
    expect(csv).toContain('# Filter: status in [FAILED]; batch SLV-2026-00981');
    expect(csv).toContain('authoritative payment ledger');
  });

  it('neutralises CSV formula injection in every text field', () => {
    const hostile = row({
      recipientName: "=cmd|'/c calc'!A1",
      failureReason: '+HYPERLINK("http://evil","click")',
      providerResultDescription: '@SUM(1+1)*cmd',
      departmentName: '-2+3+cmd',
    });
    const csv = renderFailedTransactionsCsv([hostile], metadata);
    expect(csv).toContain("'=cmd");
    expect(csv).toContain("'+HYPERLINK");
    expect(csv).toContain("'@SUM");
    expect(csv).toContain("'-2+3");
    // And no field starts a formula at the beginning of a cell.
    for (const line of csv.split('\r\n').filter((l) => l && !l.startsWith('#'))) {
      for (const cell of line.split(',')) {
        expect(cell.replace(/^"/, '')).not.toMatch(/^[=+@]/);
      }
    }
  });

  it('quotes fields containing commas, quotes and newlines', () => {
    expect(escapeCsvField('Doe, Jane')).toBe('"Doe, Jane"');
    expect(escapeCsvField('She said "hi"')).toBe('"She said ""hi"""');
    expect(escapeCsvField('line1\nline2')).toBe('"line1\nline2"');
    expect(escapeCsvField(null)).toBe('');
    expect(escapeCsvField(0)).toBe('0');
  });

  it('renders amounts as formatted KES, not raw cents', () => {
    const csv = renderFailedTransactionsCsv([row({ amountCents: 8_420_500_00 })], metadata);
    expect(csv).toContain('"8,420,500.00"');
  });

  it('produces a header-only file for an empty result set rather than an empty file', () => {
    const csv = renderFailedTransactionsCsv([], { ...metadata, rowCount: 0 });
    expect(csv).toContain(FAILED_EXPORT_HEADERS.join(','));
    expect(csv).toContain('# Rows: 0');
    expect(csv.endsWith('\r\n')).toBe(true);
  });

  it('builds a safe, deterministic filename', () => {
    expect(
      exportFilename('failed-transactions', 'Acme Holdings Ltd.', '2026-09-13T09:15:00.000Z'),
    ).toBe('failed-transactions_acme-holdings-ltd_2026-09-13_09-15-00-000.csv');
  });
});

describe('explorer query contract (§6.3, TRK-003)', () => {
  it('applies safe defaults', () => {
    const q = explorerQuerySchema.parse({});
    expect(q).toMatchObject({ sort: 'date', direction: 'desc', page: 1, pageSize: 50 });
  });

  it('rejects an unknown sort column — there is no path from user input to SQL text', () => {
    expect(() => explorerQuerySchema.parse({ sort: 'amount; DROP TABLE transactions' })).toThrow();
    expect(() => explorerQuerySchema.parse({ direction: 'asc; --' })).toThrow();
  });

  it('maps every allowlisted sort key to a fixed SQL fragment with a stable tiebreaker', () => {
    for (const key of Object.keys(SORT_COLUMNS) as (keyof typeof SORT_COLUMNS)[]) {
      const clause = buildOrderBy({ sort: key, direction: 'asc' });
      expect(clause).toBe(`${SORT_COLUMNS[key]} ASC NULLS LAST, t.id ASC`);
    }
  });

  it('caps the page size so one request cannot pull the whole ledger', () => {
    expect(() => explorerQuerySchema.parse({ pageSize: MAX_PAGE_SIZE + 1 })).toThrow();
  });

  it('describes the active filter for the audit record', () => {
    const described = describeFilter({
      status: ['FAILED', 'TIMEOUT'],
      batchId: 'b1',
      dateFrom: '2026-09-01T00:00:00Z',
      sort: 'amount',
      direction: 'desc',
    });
    expect(described.text).toContain('status in [FAILED, TIMEOUT]');
    expect(described.text).toContain('sorted by amount desc');
    expect(describeFilter({}).text).toMatch(/no filter/);
  });

  it('detects incoherent ranges', () => {
    const q = explorerQuerySchema.parse({
      dateFrom: '2026-09-30T00:00:00Z',
      dateTo: '2026-09-01T00:00:00Z',
      amountMinCents: 5000,
      amountMaxCents: 100,
    });
    expect(assertCoherentRange(q)).toHaveLength(2);
  });

  it('computes pagination correctly', () => {
    const q = explorerQuerySchema.parse({ page: 3, pageSize: 50 });
    expect(offsetFor(q)).toBe(100);
    const info = pageInfo(q, 237);
    expect(info).toMatchObject({ totalPages: 5, hasNext: true, hasPrevious: true });
    expect(pageInfo(explorerQuerySchema.parse({}), 0).totalPages).toBe(1);
  });
});

describe('risk assessment (§11)', () => {
  const now = Date.UTC(2026, 8, 13, 9, 0, 0);
  const history = (o: Partial<RecipientHistory> = {}): RecipientHistory => ({
    recipientId: 'rcp-1',
    meanAmountCents: 45_000_00,
    paymentCount: 12,
    firstPaidAt: now - 365 * 86_400_000,
    recipientCreatedAt: now - 400 * 86_400_000,
    recipientLastModifiedAt: now - 200 * 86_400_000,
    ...o,
  });

  const ins = (id: string, recipientId: string, cents: number): InstructionForRisk => ({
    instructionId: id,
    recipientId,
    msisdn: `2547${id.slice(-8).padStart(8, '0')}`,
    amountCents: cents,
    departmentId: 'dept-eng',
  });

  const baseInput = (o: Partial<Parameters<typeof assessBatchRisk>[0]> = {}) => ({
    instructions: [ins('12345001', 'rcp-1', 45_000_00)],
    history: new Map([['rcp-1', history()]]),
    priorBatchTotalsCents: [45_000_00, 45_000_00, 45_000_00],
    now,
    lastMaterialEditAt: null,
    submittedAt: null,
    unresolvedReconciliationCount: 0,
    approvalConcentration: [],
    policy: DEFAULT_RISK_POLICY,
    ...o,
  });

  it('scores a routine payroll batch as low risk', () => {
    const result = assessBatchRisk(baseInput());
    expect(result.band).toBe('LOW');
    expect(result.requiresAcknowledgement).toBe(false);
  });

  it('is deterministic — the same input always yields the same score', () => {
    const input = baseInput({ instructions: [ins('12345001', 'rcp-1', 200_000_00)] });
    expect(assessBatchRisk(input).score).toBe(assessBatchRisk(input).score);
  });

  it('flags an identical duplicate instruction as high or critical', () => {
    const dup = [
      ins('12345001', 'rcp-1', 45_000_00),
      { ...ins('12345002', 'rcp-1', 45_000_00), msisdn: '254712345001' },
    ];
    dup[0]!.msisdn = '254712345001';
    const result = assessBatchRisk(baseInput({ instructions: dup }));
    const signal = result.signals.find((s) => s.type === 'DUPLICATE_INSTRUCTION');
    expect(signal).toBeDefined();
    expect(['HIGH', 'CRITICAL']).toContain(signal!.severity);
    expect(signal!.summary).toMatch(/appears 2 times/);
    // Masked, never raw, in a finding shown across the org.
    expect(signal!.summary).not.toContain('254712345001');
  });

  it("flags an amount far outside the recipient's history, with the evidence", () => {
    const result = assessBatchRisk(
      baseInput({ instructions: [ins('12345001', 'rcp-1', 450_000_00)] }),
    );
    const signal = result.signals.find((s) => s.type === 'AMOUNT_DEVIATION')!;
    expect(signal.summary).toMatch(/10\.0× higher/);
    expect(signal.evidence.historicalMean).toBe('45,000.00');
  });

  it('flags a first payment to a brand-new recipient', () => {
    const result = assessBatchRisk(
      baseInput({
        instructions: [ins('12345009', 'rcp-new', 300_000_00)],
        history: new Map([
          [
            'rcp-new',
            history({
              recipientId: 'rcp-new',
              paymentCount: 0,
              recipientCreatedAt: now - 3_600_000,
            }),
          ],
        ]),
      }),
    );
    const signal = result.signals.find((s) => s.type === 'NEW_RECIPIENT')!;
    expect(signal.severity).toBe('HIGH');
  });

  it('flags a recipient whose bank details changed hours ago — the account-swap attack', () => {
    const result = assessBatchRisk(
      baseInput({
        history: new Map([['rcp-1', history({ recipientLastModifiedAt: now - 2 * 3_600_000 })]]),
      }),
    );
    expect(result.signals.some((s) => s.type === 'RECENTLY_MODIFIED_RECIPIENT')).toBe(true);
  });

  it('flags a batch total far from the recent baseline', () => {
    const result = assessBatchRisk(
      baseInput({ instructions: [ins('12345001', 'rcp-1', 200_000_00)] }),
    );
    expect(result.signals.some((s) => s.type === 'BATCH_TOTAL_DEVIATION')).toBe(true);
  });

  it('flags an edit made minutes before submission', () => {
    const result = assessBatchRisk(
      baseInput({ lastMaterialEditAt: now - 120_000, submittedAt: now }),
    );
    expect(result.signals.some((s) => s.type === 'LATE_EDIT')).toBe(true);
  });

  it('flags outstanding reconciliation before releasing more money', () => {
    const result = assessBatchRisk(baseInput({ unresolvedReconciliationCount: 7 }));
    const signal = result.signals.find((s) => s.type === 'UNRESOLVED_RECONCILIATION')!;
    expect(signal.severity).toBe('HIGH');
  });

  it('applies diminishing returns so a large onboarding batch is not automatically critical', () => {
    const many = Array.from({ length: 50 }, (_, i) =>
      ins(`1234${String(i).padStart(4, '0')}`, `rcp-${i}`, 10_000_00),
    );
    const result = assessBatchRisk(
      baseInput({ instructions: many, history: new Map(), priorBatchTotalsCents: [] }),
    );
    expect(result.score).toBeLessThanOrEqual(100);
    expect(result.signals.length).toBe(50);
  });

  it('keeps the score inside 0-100 and sorts signals by severity', () => {
    const result = assessBatchRisk(
      baseInput({
        instructions: [ins('12345001', 'rcp-1', 250_000_00), ins('12345001', 'rcp-1', 250_000_00)],
        unresolvedReconciliationCount: 20,
        lastMaterialEditAt: now - 1000,
        submittedAt: now,
      }),
    );
    expect(result.score).toBeGreaterThanOrEqual(0);
    expect(result.score).toBeLessThanOrEqual(100);
    const severities = result.signals.map((s) => s.severity);
    const weights = { INFO: 0, LOW: 5, MEDIUM: 15, HIGH: 30, CRITICAL: 50 };
    for (let i = 1; i < severities.length; i++) {
      expect(weights[severities[i]!]).toBeLessThanOrEqual(weights[severities[i - 1]!]);
    }
  });
});

describe('report rendering (§12.1)', () => {
  const metadata: ExportMetadata = {
    exportId: 'EXP-2026-TEST',
    organizationId: 'org-1',
    generatedAt: '2026-09-14T08:00:00.000Z',
    generatedByUserId: 'user-1',
    generatedByLevel: 'L3',
    filterDescription: 'Financial report',
    rowCount: 2,
  };

  const report: ReportDocument = {
    family: 'financial',
    title: 'Financial report',
    description: 'Disbursed and failed value for the period.',
    periodFrom: '2026-09-01T00:00:00.000Z',
    periodTo: '2026-10-01T00:00:00.000Z',
    highlights: [{ label: 'Disbursed', value: 'KES 1,500.00' }],
    sections: [
      {
        title: 'Daily movement',
        columns: [
          { key: 'day', label: 'Date' },
          { key: 'paid', label: 'Disbursed (KES)', format: 'money' },
        ],
        rows: [
          { day: '2026-09-01', paid: 100_000 },
          { day: '2026-09-02', paid: 50_000 },
        ],
      },
    ],
    narrative: null,
  };

  it('prints the period on the artefact', () => {
    const csv = renderReportCsv(report, metadata);
    expect(csv).toContain('# Period: 2026-09-01T00:00:00.000Z to 2026-10-01T00:00:00.000Z');
    expect(csv).toContain('# Disbursed: KES 1,500.00');
  });

  it('renders money columns in shillings, not cents, and quotes the thousands comma', () => {
    const csv = renderReportCsv(report, metadata);
    // Unquoted, "1,000.00" would split into two columns and shift every field after it.
    expect(csv).toContain('2026-09-01,"1,000.00"');
    expect(csv).toContain('2026-09-02,500.00');
  });

  it('separates each section with its own banner and header row', () => {
    const csv = renderReportCsv(
      {
        ...report,
        sections: [
          ...report.sections,
          {
            title: 'By batch',
            columns: [{ key: 'reference', label: 'Batch' }],
            rows: [{ reference: 'SLV-2026-00001' }],
          },
        ],
      },
      metadata,
    );
    expect(csv).toContain('# Daily movement');
    expect(csv).toContain('# By batch');
    expect(csv).toContain('SLV-2026-00001');
  });

  it('says so when a section is empty rather than leaving a blank block', () => {
    const csv = renderReportCsv(
      { ...report, sections: [{ ...report.sections[0]!, rows: [] }] },
      metadata,
    );
    expect(csv).toContain('# No rows for this section in the selected period.');
  });

  it('marks every line of AI narrative, so a pasted row keeps the warning (§12.2)', () => {
    const csv = renderReportCsv(
      {
        ...report,
        narrative: {
          text: 'September rose against August.\nEngineering contributed most of it.',
          source: 'AI_ADVISORY',
          model: 'claude-test',
        },
      },
      metadata,
    );
    const advisory = csv.split('\r\n').filter((line) => line.includes('AI ADVISORY'));
    expect(advisory).toHaveLength(2);
    for (const line of advisory) {
      expect(line).toContain('not a computed figure');
    }
  });

  it('keeps a multi-line description from breaking the comment header', () => {
    const csv = renderReportCsv({ ...report, description: 'One\nTwo' }, metadata);
    const headerLines = csv.split('\r\n').slice(0, 7);
    expect(headerLines.every((line) => line.startsWith('#'))).toBe(true);
    expect(csv).toContain('# One Two');
  });

  it('renders a null cell as empty and a money cell from a numeric string', () => {
    expect(formatReportCell(null, 'money')).toBe('');
    expect(formatReportCell(undefined, 'text')).toBe('');
    expect(formatReportCell('250000', 'money')).toBe('2,500.00');
    expect(formatReportCell('SLV-1', undefined)).toBe('SLV-1');
    expect(formatReportCell(7, 'number')).toBe('7');
  });
});

describe('retrying a failed payment carries a new fingerprint (§9.3)', () => {
  const base = {
    organizationId: 'org-1',
    batchId: 'batch-1',
    instructionId: 'ins-1',
    batchVersion: 3,
    msisdn: '254712345678',
    amountCents: 150_000,
    manifestHash: 'a'.repeat(64),
  };

  it('leaves the original execution fingerprint byte-identical', async () => {
    const original = await instructionFingerprint(base);
    // An absent retry sequence and an explicit zero must both mean "the first attempt",
    // or an existing claim would stop matching after this field was added.
    expect(await instructionFingerprint({ ...base, retrySequence: 0 })).toBe(original);
  });

  it('gives each deliberate re-attempt a distinct claim', async () => {
    const original = await instructionFingerprint(base);
    const first = await instructionFingerprint({ ...base, retrySequence: 1 });
    const second = await instructionFingerprint({ ...base, retrySequence: 2 });
    expect(new Set([original, first, second]).size).toBe(3);
  });

  it('is deterministic, so the same retry cannot be claimed twice', async () => {
    expect(await instructionFingerprint({ ...base, retrySequence: 1 })).toBe(
      await instructionFingerprint({ ...base, retrySequence: 1 }),
    );
  });
});
